FROM nginx:alpine
# Конфиг nginx (можно переопределить через build arg)
ARG NGINX_CONF=nginx-prod.conf
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf
# SSL сертификаты
COPY certs/nginx.crt /etc/nginx/certs/nginx.crt
COPY certs/nginx.key /etc/nginx/certs/nginx.key
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
