FROM nginx:alpine
# Конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
# SSL сертификаты (генерируются через mkcert перед сборкой)
COPY certs/nginx.crt /etc/nginx/certs/nginx.crt
COPY certs/nginx.key /etc/nginx/certs/nginx.key
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
